CREATE DATABASE judo;

USE judo;

CREATE TABLE judoka(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
age INT NOT NULL,
gender TINYINT NOT NULL,
id_belt VARCHAR(16),
CONSTRAINT fk_id_belt FOREIGN KEY(id_belt) REFERENCES belt(color) ON DELETE CASCADE ON UPDATE CASCADE


);

CREATE TABLE belt(
color VARCHAR(16) PRIMARY KEY
);

CREATE TABLE competition(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
start_date DATE NOT NULL,
end_date DATE NOT NULL
);

CREATE TABLE judoka_competition(
id_competition INT NOT NULL,
CONSTRAINT fk_id_competition FOREIGN KEY(id_competition) REFERENCES competition(id) ON DELETE CASCADE ON UPDATE CASCADE,
id_judoka INT NOT NULL,
CONSTRAINT fk_id_judoka FOREIGN KEY(id_judoka) REFERENCES judoka(id) ON DELETE CASCADE ON UPDATE CASCADE
);
